<?php

use Illuminate\Database\Seeder;
use App\WindowSize;

class WindowSizeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
WindowSize::updateOrCreate(['orderFirst' => '2',            'orderThen' => '3.4',       'size' => '2 X 3.5 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.0625',       'orderThen' => '4.5',       'size' => '1 1/16 x 4 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.5',       'size' => '1 1/2 X 3 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.5',       'size' => '1 1/2 x 3 1/2  (1)  Oval- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.75',      'size' => '1 1/2 X 3 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.625',     'size' => '1 1/2 X 3 5/8  (1)  pistol Right- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.625',     'size' => '1 1/2 X 3 5/8 (1)  regular- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '4',         'size' => '1 1/2 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '4.5',       'size' => '1 1/2 X 4 1/2(2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '4.25',      'size' => '1 1/2 X 4 1/4(3)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '4.125',     'size' => '1 1/2 X 4 1/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '5.25',      'size' => '1 1/2 X 5 1/4  (1)  pistol- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '5.625',     'size' => '1 1/2 X 5 3/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '5.875',     'size' => '1 1/2 x 5 7/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '2.75',      'size' => '1 1/4 X 2 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3',         'size' => '1 1/4 X 3 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.5',       'size' => '1 1/4 X 3 1/2     (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.25',      'size' => '1 1/4 X 3 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.75',      'size' => '1 1/4 X 3 3/4     (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.375',     'size' => '1 1/4 X 3 3/8     (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.875',     'size' => '1 1/4 X 3 7/8     (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4',         'size' => '1 1/4 X 4    (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.5',       'size' => '1 1/4 X 4 1/2     (3)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.25',      'size' => '1 1/4 X 4 1/4       (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.125',     'size' => '1 1/4 x 4 1/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.75',      'size' => '1 1/4 X 4 3/4   (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.875',     'size' => '1 1/4 X 4 7/8     (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '5.5',       'size' => '1 1/4 X 5 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '5.375',     'size' => '1 1/4 X 5 3/8  (1)  Pistol Die- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '7',         'size' => '1 1/4 x 7 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '9',         'size' => '1 1/4 x 7/8 x 9 (1)  - WRW Double Perf']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '3.5',       'size' => '1 1/8 X 3 1/2      (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '3.25',      'size' => '1 1/8 X 3 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '3.75',      'size' => '1 1/8 X 3 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '3.625',     'size' => '1 1/8 X 3 5/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '3.875',     'size' => '1 1/8 X 3 7/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4',         'size' => '1 1/8 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4.5',       'size' => '1 1/8 X 4 1/2      (4)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4.25',      'size' => '1 1/8 X 4 1/4      (3)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4.125',     'size' => '1 1/8 X 4 1/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4.75',      'size' => '1 1/8 X 4 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.40625',      'orderThen' => '2.71875',   'size' => '1 13/32 X 2 23/32  (1)  Oval- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '3.5',       'size' => '1 3/4 X 3 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '3.75',      'size' => '1 3/4 X 3 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '4',         'size' => '1 3/4 X 4  (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '4.25',      'size' => '1 3/4 X 4 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '4.375',     'size' => '1 3/4 X 4 3/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.5',       'size' => '1 3/8 X 3 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.75',      'size' => '1 3/8 X 3 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.375',     'size' => '1 3/8 X 3 3/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.625',     'size' => '1 3/8 X 3 5/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.4375',    'size' => '1 3/8 X 3 7/16 (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.875',     'size' => '1 3/8 X 3 7/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '4',         'size' => '1 3/8 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '4.25',      'size' => '1 3/8 X 4 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '5.75',      'size' => '1 3/8 X 5 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '0',          'size' => '1 5/8 (1)  Circle Die- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '3.75',      'size' => '1 5/8 X 3 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '3.625',     'size' => '1 5/8 X 3 5/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '4',         'size' => '1 5/8 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '4.5	',      'size' => '1 5/8 X 4 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '4.25',      'size' => '1 5/8 X 4 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.4375',       'orderThen' => '4',         'size' => '1 7/16 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.875',        'orderThen' => '3.75',      'size' => '1 7/8 X 3 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.875',        'orderThen' => '5.375',     'size' => '1 7/8 x 5 3/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '2.25',      'size' => '1 X 2 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '2.75',      'size' => '1 X 2 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3',         'size' => '1 X 3  (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.5',       'size' => '1 X 3 1/2   (3)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.25',      'size' => '1 X 3 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.75',      'size' => '1 X 3 3/4   (3)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.375',     'size' => '1 X 3 3/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '0.75',      'size' => '1 X 3/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '4',         'size' => '1 X 4 (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '4.25',      'size' => '1 X 4 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '5',         'size' => '1 X 5 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '7.25',      'size' => '1 X 7 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.5',          'orderThen' => '2.5',       'size' => '1/2 X 2 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.0625',       'orderThen' => '3.3125',    'size' => '2 1/16 X 3 5/16 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.5',          'orderThen' => '7.9375',    'size' => '2 1/2 X 7 15/16  (1)  spec slitter- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.25',         'orderThen' => '2',         'size' => '2 1/4 X 2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.25',         'orderThen' => '4.25',      'size' => '2 1/4 X 4 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.25',         'orderThen' => '4.625',     'size' => '2 1/4 X 4 5/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.25',         'orderThen' => '5.875',     'size' => '2 1/4 X 5 7/8  (1)  pistol- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.25',         'orderThen' => '6.75',      'size' => '2 1/4 x 6 3/4  (1)  Pistol  Fenske- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.75',         'orderThen' => '3.5	',      'size' => '2 3/4 X 3 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.75',         'orderThen' => '6',         'size' => '2 3/4 X 6 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.75',         'orderThen' => '6.25',      'size' => '2 3/4 X 6 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.625',        'orderThen' => '4',         'size' => '2 5/8 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.625',        'orderThen' => '6.5625',    'size' => '2 5/8 x 6 9/16 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.875',        'orderThen' => '7.5	',      'size' => '2 7/8 X 7 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2',            'orderThen' => '4.5	',      'size' => '2 X 4 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3.0625	',      'orderThen' => '8',         'size' => '3 1/16 X 8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3.5',          'orderThen' => '6.34375',   'size' => '3 1/2 X 6 11/32  (1)  purse die- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3.1875',       'orderThen' => '3',         'size' => ' 3/16 Circle- (1) WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3.75',         'orderThen' => '1.125',     'size' => '3 3/4 x 1 1/8  (1)  vertical mounted- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3.75',         'orderThen' => '6',         'size' => '3 3/4 X 6 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3',            'orderThen' => '2',         'size' => '3 X 2  (1)  Verticle- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3',            'orderThen' => '4',         'size' => '3 X 4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.75',         'orderThen' => '1',         'size' => '3/4 X 1  (3)  Verticle  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.75',         'orderThen' => '8.3125',    'size' => '3/4 X 8 5/16 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '4.75',         'orderThen' => '8',         'size' => '4 3/4 X 8  (1)  vert slitter- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '5.5',          'orderThen' => '8.5',       'size' => '5 1/2 X 8 1/2 (1)  vert slitter- WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.625',        'orderThen' => '2.125',     'size' => '5/8 X 2 1/8 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.625',        'orderThen' => '3.5',       'size' => '5/8 X 3 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.625',        'orderThen' => '0.875',     'size' => '5/8 X 7/8    (2)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.875',        'orderThen' => '2.5',       'size' => '7/8 X 2 1/2 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '0.875',        'orderThen' => '3.25',      'size' => '7/8 X 3 1/4 (1)  - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.5',       'size' => '1 1/2 X 3 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '3.25',      'size' => '1 1/2 X 3 1/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '4',         'size' => '1 1/2 X 4   (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.5',          'orderThen' => '4.5',       'size' => '1 1/2 x 4 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.5',       'size' => '1 1/4 X 3 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '3.75',      'size' => '1 1/4 X 3 3/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4',         'size' => '1 1/4 X 4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.25',      'size' => '1 1/4 X 4 1/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '5',         'size' => '1 1/4 X 5 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '5.5	',      'size' => '1 1/4 X 5 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '3.75',      'size' => '1 1/8 X 3 3/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4.5',       'size' => '1 1/8 X 4 1/2  (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '4.75',      'size' => '1 1/8 X 4 3/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.125',        'orderThen' => '5',         'size' => '1 1/8 x 5 (1) - 31J - H round cnr']);
WindowSize::updateOrCreate(['orderFirst' => '1.25',         'orderThen' => '4.5',       'size' => '1 1/4 x 4 1/2 (1) -31J -  H']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '3.5',       'size' => '1 3/4 X 3 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.75',         'orderThen' => '4.5',       'size' => '1 3/4 x 4 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '3.3125',    'size' => '1 3/8 X 3 5/16 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '4',         'size' => '1 3/8 X 4   (1) - 31J -  H']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '4.25',      'size' => '1 3/8 X 4 1/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.3125',       'orderThen' => '3.4375',    'size' => '1 5/16 X 3 7/16 (1) - 31J -  H']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '2.875',     'size' => '1 5/8 X 2 7/8 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '3.5',       'size' => '1 5/8 X 3 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.625',        'orderThen' => '4.75',      'size' => '1 5/8 X 4 3/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.4375',       'orderThen' => '4.125',     'size' => '1 7/16 X 4 1/8 (2) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1.875',        'orderThen' => '3.75',      'size' => '1 7/8 X 3 3/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.5',       'size' => '1 X 3 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.25',      'size' => '1 X 3 1/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.75',      'size' => '1 X 3 3/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '3.625',     'size' => '1 X 3 5/8 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '4.5',       'size' => '1 X 4 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '2.5',          'orderThen' => '4.5',       'size' => '2 1/2 X 4 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '2.75',         'orderThen' => '5',         'size' => '2 3/4 X 5 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '2.375',        'orderThen' => '3.625',     'size' => '2 3/8 X 3 5/8 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '2',            'orderThen' => '3',         'size' => '2 X 3 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '2',            'orderThen' => '4',         'size' => '2 x 4 (1) - 31J -H']);
WindowSize::updateOrCreate(['orderFirst' => '2',            'orderThen' => '6.5',       'size' => '2 X 6 1/2 (1) - 31J -H']);
WindowSize::updateOrCreate(['orderFirst' => '3.5',          'orderThen' => '1.125',     'size' => '3 1/2 X 1 1/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3.5',          'orderThen' => '1.625',     'size' => '3 1/2 X 1 5/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3.25',         'orderThen' => '1.25',      'size' => '3 1/4 X 1 1/4 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3.75',         'orderThen' => '1.5	',      'size' => '3 3/4 X 1 1/2 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3.75',         'orderThen' => '1.25',      'size' => '3 3/4 X 1 1/4 (2) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3.625',        'orderThen' => '1.375',     'size' => '3 5/8 X 1 3/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3.4375',       'orderThen' => '1.3125',    'size' => '3 7/16 X 1 5/16 (1) - 31J -  V']);
WindowSize::updateOrCreate(['orderFirst' => '3',            'orderThen' => '1.25',      'size' => '3 X 1 1/4 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '3',            'orderThen' => '3',         'size' => '3 X 3 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '3',            'orderThen' => '5.25',      'size' => '3 X 5 1/4 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '0.75',         'orderThen' => '3.5',       'size' => '3/4 x 3 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '4.5',          'orderThen' => '1.125',     'size' => '4 1/2 X 1 1/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '4.5',          'orderThen' => '1.625',     'size' => '4 1/2 x 1 5/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '4.5',          'orderThen' => '0.',        'size' => '4 1/2 X 7/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '4.875',        'orderThen' => '1.625',     'size' => '4 7/8 X 1 5/8 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '4',            'orderThen' => '1.5',       'size' => '4 X 1 1/2 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '4',            'orderThen' => '1.25',      'size' => '4 X 1 1/4 (1) - 31J - V']);
WindowSize::updateOrCreate(['orderFirst' => '0.875',        'orderThen' => '2.5	',      'size' => '7/8 X 2 1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '0.875',        'orderThen' => '3.375',     'size' => '7/8 X 3 3/8 (1) - 31J -  H']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '4.5',       'size' => '1 3/8 X 4 1/2 (1) - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.625',        'orderThen' => '1.625',     'size' => '2 5/8 x 1 5/8 (1) - Vertical WRW']);
WindowSize::updateOrCreate(['orderFirst' => '1.375',        'orderThen' => '4.5',       'size' => '1-3/8 x 4-1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '2.75',         'orderThen' => '4.5',       'size' => '2-3/4 X 4-1/2 (1) - 31J - H']);
WindowSize::updateOrCreate(['orderFirst' => '1',            'orderThen' => '4.5',       'size' => '1 X 4-1/2 (1) WRW']);
WindowSize::updateOrCreate(['orderFirst' => '3.5',          'orderThen' => '7',         'size' => '3-1/2 x 7  (1) vert slitter - WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.5',          'orderThen' => '5',         'size' => '2 1/2 x 5 (1) 31J - vert slitter']);
WindowSize::updateOrCreate(['orderFirst' => '2',            'orderThen' => '6.875',     'size' => '2 x 6-7/8 (1) WRW']);
WindowSize::updateOrCreate(['orderFirst' => '2.0625',       'orderThen' => '4',         'size' => '2 1/16 X4 - WRW Eagle Direct']);
WindowSize::updateOrCreate(['orderFirst' => '4.5',          'orderThen' => '1.375',     'size' => '1 3/8 x 4 1/2 (1) pull tab perf']);
    }
}
